# Importing Pandas

In [1]:
import pandas as pd #pandas ko short main pd se change kia

### Reading a CSV File

In [2]:
df=pd.read_csv("heart2.csv")
df.reset_index()

,index,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,target
0,0,40.0,1,2,140,289,0,0,172,0,0.0,1,0
1,1,NaN,0,3,160,180,0,0,156,0,1.0,2,1
2,2,37.0,1,2,130,283,0,1,98,0,0.0,1,0
3,3,48.0,0,4,138,214,0,0,108,1,1.5,2,1
4,4,54.0,1,3,150,195,0,0,122,0,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1185,1185,45.0,1,1,110,264,0,0,132,0,1.2,2,1
1186,1186,68.0,1,4,144,193,1,0,141,0,3.4,2,1
1187,1187,57.0,1,4,130,131,0,0,115,1,1.2,2,1
1188,1188,57.0,0,2,130,236,0,2,174,0,0.0,2,1
1189,1189,38.0,1,3,138,175,0,0,173,0,0.0,1,0

### To view first 5 rows

In [3]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,target
0,40.0,1,2,140,289,0,0,172,0,0.0,1,0
1,NaN,0,3,160,180,0,0,156,0,1.0,2,1
2,37.0,1,2,130,283,0,1,98,0,0.0,1,0
3,48.0,0,4,138,214,0,0,108,1,1.5,2,1
4,54.0,1,3,150,195,0,0,122,0,0.0,1,0

### To view last 5 rows

In [4]:
df.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,target
1185,45.0,1,1,110,264,0,0,132,0,1.2,2,1
1186,68.0,1,4,144,193,1,0,141,0,3.4,2,1
1187,57.0,1,4,130,131,0,0,115,1,1.2,2,1
1188,57.0,0,2,130,236,0,2,174,0,0.0,2,1
1189,38.0,1,3,138,175,0,0,173,0,0.0,1,0

### Dataset Shape
checking rows and columns

In [5]:
df.shape

(1190, 12)

### Checking columns

In [6]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'target'],
      dtype='str')

### Information About Dataset

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1190 entries, 0 to 1189
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1183 non-null   float64
 1   sex       1190 non-null   int64
 2   cp        1190 non-null   int64
 3   trestbps  1190 non-null   int64
 4   chol      1190 non-null   int64
 5   fbs       1190 non-null   int64
 6   restecg   1190 non-null   int64
 7   thalach   1190 non-null   int64
 8   exang     1190 non-null   int64
 9   oldpeak   1190 non-null   float64
 10  slope     1190 non-null   int64
 11  target    1190 non-null   int64
dtypes: float64(2), int64(10)
memory usage: 111.7 KB

### Checking Data Types

In [8]:
df.dtypes

age         float64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
target        int64
dtype: object

### Handling Missing Values

In [9]:
df.isnull().sum() #checking null values ager kam hay to drop warna fill

age         7
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
target      0
dtype: int64

### Drop missing values
To drop rows with missing values

In [10]:
df.dropna() #dropna drop the row with missing value But hum direct drop nhi krengee fill karnee ki koshish krengee
df.isnull().sum()

age         7
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
target      0
dtype: int64

### Fill missing values
Handling missing values is an important part of Exploratory Data Analysis

In [11]:
df["age"]=df["age"].fillna(df["age"].mean()) #hamree pass age main 7 values null hay to hum age ka mean nekal krr fill krthee hay 
df.isnull().sum() #age ka mean 53 hay to null values 53 se fill huwee hay

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
target      0
dtype: int64

In [12]:
df.head(20) #let see the index=1 and index=17

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,target
0,40.000000,1,2,140,289,0,0,172,0,0.0,1,0
1,53.757396,0,3,160,180,0,0,156,0,1.0,2,1
2,37.000000,1,2,130,283,0,1,98,0,0.0,1,0
3,48.000000,0,4,138,214,0,0,108,1,1.5,2,1
4,54.000000,1,3,150,195,0,0,122,0,0.0,1,0
5,39.000000,1,3,120,339,0,0,170,0,0.0,1,0
6,45.000000,0,2,130,237,0,0,170,0,0.0,1,0
7,54.000000,1,2,110,208,0,0,142,0,0.0,1,0
8,37.000000,1,4,140,207,0,0,130,1,1.5,2,1
9,48.000000,0,2,120,284,0,0,120,0,0.0,1,0
10,37.000000,0,3,130,211,0,0,142,0,0.0,1,0
11,58.000000,1,2,136,164,0,1,99,1,2.0,2,1
12,39.000000,1,2,120,204,0,0,145,0,0.0,1,0
13,49.000000,1,4,140,234,0,0,140,1,1.0,2,1
14,42.000000,0,3,115,211,0,1,137,0,0.0,1,0
15,54.000000,0,2,120,273,0,0,150,0,1.5,2,0
16,38.000000,1,4,110,196,0,0,166,0,0.0,2,1
17,53.757396,0,2,120,201,0,0,165,0,0.0,1,0
18,60.000000,1,4,100,248,0,0,125,0,1.0,2,1
19,36.000000,1,2,120,267,0,0,160,0,3.0,2,1

In [24]:
df.describe().reset_index() # Count ,Mean,Standard deviation,Minimum,Maximum,Percentiles

,index,Age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,target
0,count,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000
1,mean,53.757396,0.763866,3.232773,132.153782,210.363866,0.213445,0.698319,139.732773,0.387395,0.922773,1.624370,0.528571
2,std,9.339291,0.424884,0.935480,18.368823,101.420489,0.409912,0.870359,25.517636,0.487360,1.086337,0.610459,0.499393
3,min,28.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,60.000000,0.000000,-2.600000,0.000000,0.000000
4,25%,47.000000,1.000000,3.000000,120.000000,188.000000,0.000000,0.000000,121.000000,0.000000,0.000000,1.000000,0.000000
5,50%,54.000000,1.000000,4.000000,130.000000,229.000000,0.000000,0.000000,140.500000,0.000000,0.600000,2.000000,1.000000
6,75%,60.000000,1.000000,4.000000,140.000000,269.750000,0.000000,2.000000,160.000000,1.000000,1.600000,2.000000,1.000000
7,max,77.000000,1.000000,4.000000,200.000000,603.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,1.000000

### Checking Unique Values

In [14]:
df["age"].unique() #Checking unique values

array([40.        , 53.75739645, 37.        , 48.        , 54.        ,
       39.        , 45.        , 58.        , 49.        , 42.        ,
       38.        , 60.        , 36.        , 43.        , 44.        ,
       53.        , 52.        , 51.        , 56.        , 41.        ,
       32.        , 65.        , 35.        , 59.        , 50.        ,
       47.        , 31.        , 46.        , 57.        , 55.        ,
       63.        , 66.        , 34.        , 33.        , 61.        ,
       29.        , 62.        , 28.        , 30.        , 74.        ,
       68.        , 72.        , 64.        , 69.        , 67.        ,
       73.        , 70.        , 77.        , 75.        , 76.        ,
       71.        ])

In [15]:
df["age"].nunique() #Number of unique values

51

### Value Counts

In [16]:
df["sex"].value_counts() # female zada thii ya male tadad batata hay

sex
1    909
0    281
Name: count, dtype: int64

In [17]:
df["sex"].count() #All count male+female

np.int64(1190)

###  Renaming Columns

In [18]:
df.rename(columns={
    "age":"Age"
},inplace=True)
df

,Age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,target
0,40.000000,1,2,140,289,0,0,172,0,0.0,1,0
1,53.757396,0,3,160,180,0,0,156,0,1.0,2,1
2,37.000000,1,2,130,283,0,1,98,0,0.0,1,0
3,48.000000,0,4,138,214,0,0,108,1,1.5,2,1
4,54.000000,1,3,150,195,0,0,122,0,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1185,45.000000,1,1,110,264,0,0,132,0,1.2,2,1
1186,68.000000,1,4,144,193,1,0,141,0,3.4,2,1
1187,57.000000,1,4,130,131,0,0,115,1,1.2,2,1
1188,57.000000,0,2,130,236,0,2,174,0,0.0,2,1
1189,38.000000,1,3,138,175,0,0,173,0,0.0,1,0

In [19]:
#Loding new dataset
df2=pd.read_csv("sales_data.csv")
df2

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1010,2023-04-15,Charlie,North,4733.88,4,Food,4943.03,5442.15,Returning,0.29,Cash,Online,North-Charlie
996,1067,2023-09-07,Bob,North,4716.36,37,Clothing,1754.32,1856.40,New,0.21,Bank Transfer,Retail,North-Bob
997,1018,2023-04-27,David,South,7629.70,17,Clothing,355.72,438.27,Returning,0.06,Bank Transfer,Online,South-David
998,1100,2023-12-20,David,West,1629.47,39,Electronics,3685.03,3743.39,New,0.01,Bank Transfer,Online,West-David
999,1086,2023-08-16,Alice,East,4923.93,48,Food,2632.58,2926.68,Returning,0.14,Cash,Online,East-Alice

In [20]:

#Convert to lowercase:
df2["Product_Category"] = df2["Product_Category"].str.lower()

#Convert to uppercase:
df2["Product_Category"] = df2["Product_Category"].str.upper()

#Remove extra spaces:
df2["Product_Category"] = df2["Product_Category"].str.strip()

df2

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,FURNITURE,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,FURNITURE,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,FOOD,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,CLOTHING,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,ELECTRONICS,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1010,2023-04-15,Charlie,North,4733.88,4,FOOD,4943.03,5442.15,Returning,0.29,Cash,Online,North-Charlie
996,1067,2023-09-07,Bob,North,4716.36,37,CLOTHING,1754.32,1856.40,New,0.21,Bank Transfer,Retail,North-Bob
997,1018,2023-04-27,David,South,7629.70,17,CLOTHING,355.72,438.27,Returning,0.06,Bank Transfer,Online,South-David
998,1100,2023-12-20,David,West,1629.47,39,ELECTRONICS,3685.03,3743.39,New,0.01,Bank Transfer,Online,West-David
999,1086,2023-08-16,Alice,East,4923.93,48,FOOD,2632.58,2926.68,Returning,0.14,Cash,Online,East-Alice

### Changing Data Types

#### Check data types:

In [21]:

df2.dtypes

Product_ID                int64
Sale_Date                   str
Sales_Rep                   str
Region                      str
Sales_Amount            float64
Quantity_Sold             int64
Product_Category            str
Unit_Cost               float64
Unit_Price              float64
Customer_Type               str
Discount                float64
Payment_Method              str
Sales_Channel               str
Region_and_Sales_Rep        str
dtype: object

#### Convert column type:

In [22]:
df2["Discount"] = df2["Discount"].astype(int) #for Discount float64 change into int64

In [23]:
df2.dtypes # Discount changed into int

Product_ID                int64
Sale_Date                   str
Sales_Rep                   str
Region                      str
Sales_Amount            float64
Quantity_Sold             int64
Product_Category            str
Unit_Cost               float64
Unit_Price              float64
Customer_Type               str
Discount                  int64
Payment_Method              str
Sales_Channel               str
Region_and_Sales_Rep        str
dtype: object

In [ ]:
df2["Sale_Date"] = pd.to_datetime(df2["Sale_Date"])
df2.dtypes

Product_ID                       int64
Sale_Date               datetime64[us]
Sales_Rep                          str
Region                             str
Sales_Amount                   float64
Quantity_Sold                    int64
Product_Category                   str
Unit_Cost                      float64
Unit_Price                     float64
Customer_Type                      str
Discount                         int64
Payment_Method                     str
Sales_Channel                      str
Region_and_Sales_Rep               str
dtype: object